
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"  # Formato correcto para mapeo de puertos
    environment:       # Corregido el nombre de la sección
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db  # Espacio añadido después del -